// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/client/models"
)

// DeleteUsersIDReader is a Reader for the DeleteUsersID structure.
type DeleteUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteUsersIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /users/{id}] DeleteUsersID", response, response.Code())
	}
}

// NewDeleteUsersIDOK creates a DeleteUsersIDOK with default headers values
func NewDeleteUsersIDOK() *DeleteUsersIDOK {
	return &DeleteUsersIDOK{}
}

/*
DeleteUsersIDOK describes a response with status code 200, with default header values.

success
*/
type DeleteUsersIDOK struct {
	Payload *models.ResponseBodyTaskResource
}

// IsSuccess returns true when this delete users Id o k response has a 2xx status code
func (o *DeleteUsersIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete users Id o k response has a 3xx status code
func (o *DeleteUsersIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id o k response has a 4xx status code
func (o *DeleteUsersIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete users Id o k response has a 5xx status code
func (o *DeleteUsersIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users Id o k response a status code equal to that given
func (o *DeleteUsersIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete users Id o k response
func (o *DeleteUsersIDOK) Code() int {
	return 200
}

func (o *DeleteUsersIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdOK %s", 200, payload)
}

func (o *DeleteUsersIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdOK %s", 200, payload)
}

func (o *DeleteUsersIDOK) GetPayload() *models.ResponseBodyTaskResource {
	return o.Payload
}

func (o *DeleteUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyTaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDForbidden creates a DeleteUsersIDForbidden with default headers values
func NewDeleteUsersIDForbidden() *DeleteUsersIDForbidden {
	return &DeleteUsersIDForbidden{}
}

/*
DeleteUsersIDForbidden describes a response with status code 403, with default header values.

home directory deletion is rejected by the server due to, for example, home directory is not empty
*/
type DeleteUsersIDForbidden struct {
	Payload *models.ResponseBody403
}

// IsSuccess returns true when this delete users Id forbidden response has a 2xx status code
func (o *DeleteUsersIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete users Id forbidden response has a 3xx status code
func (o *DeleteUsersIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id forbidden response has a 4xx status code
func (o *DeleteUsersIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete users Id forbidden response has a 5xx status code
func (o *DeleteUsersIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users Id forbidden response a status code equal to that given
func (o *DeleteUsersIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete users Id forbidden response
func (o *DeleteUsersIDForbidden) Code() int {
	return 403
}

func (o *DeleteUsersIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdForbidden %s", 403, payload)
}

func (o *DeleteUsersIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdForbidden %s", 403, payload)
}

func (o *DeleteUsersIDForbidden) GetPayload() *models.ResponseBody403 {
	return o.Payload
}

func (o *DeleteUsersIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody403)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDNotFound creates a DeleteUsersIDNotFound with default headers values
func NewDeleteUsersIDNotFound() *DeleteUsersIDNotFound {
	return &DeleteUsersIDNotFound{}
}

/*
DeleteUsersIDNotFound describes a response with status code 404, with default header values.

user or user's home directory not found
*/
type DeleteUsersIDNotFound struct {
	Payload string
}

// IsSuccess returns true when this delete users Id not found response has a 2xx status code
func (o *DeleteUsersIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete users Id not found response has a 3xx status code
func (o *DeleteUsersIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id not found response has a 4xx status code
func (o *DeleteUsersIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete users Id not found response has a 5xx status code
func (o *DeleteUsersIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users Id not found response a status code equal to that given
func (o *DeleteUsersIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete users Id not found response
func (o *DeleteUsersIDNotFound) Code() int {
	return 404
}

func (o *DeleteUsersIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNotFound %s", 404, payload)
}

func (o *DeleteUsersIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdNotFound %s", 404, payload)
}

func (o *DeleteUsersIDNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersIDInternalServerError creates a DeleteUsersIDInternalServerError with default headers values
func NewDeleteUsersIDInternalServerError() *DeleteUsersIDInternalServerError {
	return &DeleteUsersIDInternalServerError{}
}

/*
DeleteUsersIDInternalServerError describes a response with status code 500, with default header values.

failure
*/
type DeleteUsersIDInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this delete users Id internal server error response has a 2xx status code
func (o *DeleteUsersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete users Id internal server error response has a 3xx status code
func (o *DeleteUsersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users Id internal server error response has a 4xx status code
func (o *DeleteUsersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete users Id internal server error response has a 5xx status code
func (o *DeleteUsersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete users Id internal server error response a status code equal to that given
func (o *DeleteUsersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete users Id internal server error response
func (o *DeleteUsersIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteUsersIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdInternalServerError %s", 500, payload)
}

func (o *DeleteUsersIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUsersIdInternalServerError %s", 500, payload)
}

func (o *DeleteUsersIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *DeleteUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
