// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTasksTypeIDParams creates a new GetTasksTypeIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTasksTypeIDParams() *GetTasksTypeIDParams {
	return &GetTasksTypeIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTasksTypeIDParamsWithTimeout creates a new GetTasksTypeIDParams object
// with the ability to set a timeout on a request.
func NewGetTasksTypeIDParamsWithTimeout(timeout time.Duration) *GetTasksTypeIDParams {
	return &GetTasksTypeIDParams{
		timeout: timeout,
	}
}

// NewGetTasksTypeIDParamsWithContext creates a new GetTasksTypeIDParams object
// with the ability to set a context for a request.
func NewGetTasksTypeIDParamsWithContext(ctx context.Context) *GetTasksTypeIDParams {
	return &GetTasksTypeIDParams{
		Context: ctx,
	}
}

// NewGetTasksTypeIDParamsWithHTTPClient creates a new GetTasksTypeIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTasksTypeIDParamsWithHTTPClient(client *http.Client) *GetTasksTypeIDParams {
	return &GetTasksTypeIDParams{
		HTTPClient: client,
	}
}

/* GetTasksTypeIDParams contains all the parameters to send to the API endpoint
   for the get tasks type ID operation.

   Typically these are written to a http.Request.
*/
type GetTasksTypeIDParams struct {

	/* ID.

	   task identifier
	*/
	ID string

	/* Type.

	   task type
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tasks type ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTasksTypeIDParams) WithDefaults() *GetTasksTypeIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tasks type ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTasksTypeIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tasks type ID params
func (o *GetTasksTypeIDParams) WithTimeout(timeout time.Duration) *GetTasksTypeIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tasks type ID params
func (o *GetTasksTypeIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tasks type ID params
func (o *GetTasksTypeIDParams) WithContext(ctx context.Context) *GetTasksTypeIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tasks type ID params
func (o *GetTasksTypeIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tasks type ID params
func (o *GetTasksTypeIDParams) WithHTTPClient(client *http.Client) *GetTasksTypeIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tasks type ID params
func (o *GetTasksTypeIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get tasks type ID params
func (o *GetTasksTypeIDParams) WithID(id string) *GetTasksTypeIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get tasks type ID params
func (o *GetTasksTypeIDParams) SetID(id string) {
	o.ID = id
}

// WithType adds the typeVar to the get tasks type ID params
func (o *GetTasksTypeIDParams) WithType(typeVar string) *GetTasksTypeIDParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get tasks type ID params
func (o *GetTasksTypeIDParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetTasksTypeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
