// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectsIDParams creates a new GetProjectsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectsIDParams() *GetProjectsIDParams {
	return &GetProjectsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectsIDParamsWithTimeout creates a new GetProjectsIDParams object
// with the ability to set a timeout on a request.
func NewGetProjectsIDParamsWithTimeout(timeout time.Duration) *GetProjectsIDParams {
	return &GetProjectsIDParams{
		timeout: timeout,
	}
}

// NewGetProjectsIDParamsWithContext creates a new GetProjectsIDParams object
// with the ability to set a context for a request.
func NewGetProjectsIDParamsWithContext(ctx context.Context) *GetProjectsIDParams {
	return &GetProjectsIDParams{
		Context: ctx,
	}
}

// NewGetProjectsIDParamsWithHTTPClient creates a new GetProjectsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectsIDParamsWithHTTPClient(client *http.Client) *GetProjectsIDParams {
	return &GetProjectsIDParams{
		HTTPClient: client,
	}
}

/* GetProjectsIDParams contains all the parameters to send to the API endpoint
   for the get projects ID operation.

   Typically these are written to a http.Request.
*/
type GetProjectsIDParams struct {

	/* ID.

	   project identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get projects ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectsIDParams) WithDefaults() *GetProjectsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get projects ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get projects ID params
func (o *GetProjectsIDParams) WithTimeout(timeout time.Duration) *GetProjectsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get projects ID params
func (o *GetProjectsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get projects ID params
func (o *GetProjectsIDParams) WithContext(ctx context.Context) *GetProjectsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get projects ID params
func (o *GetProjectsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get projects ID params
func (o *GetProjectsIDParams) WithHTTPClient(client *http.Client) *GetProjectsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get projects ID params
func (o *GetProjectsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get projects ID params
func (o *GetProjectsIDParams) WithID(id string) *GetProjectsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get projects ID params
func (o *GetProjectsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
