// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/client/models"
)

// GetProjectsReader is a Reader for the GetProjects structure.
type GetProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetProjectsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /projects] GetProjects", response, response.Code())
	}
}

// NewGetProjectsOK creates a GetProjectsOK with default headers values
func NewGetProjectsOK() *GetProjectsOK {
	return &GetProjectsOK{}
}

/*
GetProjectsOK describes a response with status code 200, with default header values.

success
*/
type GetProjectsOK struct {
	Payload *models.ResponseBodyProjects
}

// IsSuccess returns true when this get projects o k response has a 2xx status code
func (o *GetProjectsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get projects o k response has a 3xx status code
func (o *GetProjectsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get projects o k response has a 4xx status code
func (o *GetProjectsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get projects o k response has a 5xx status code
func (o *GetProjectsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get projects o k response a status code equal to that given
func (o *GetProjectsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get projects o k response
func (o *GetProjectsOK) Code() int {
	return 200
}

func (o *GetProjectsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects][%d] getProjectsOK %s", 200, payload)
}

func (o *GetProjectsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects][%d] getProjectsOK %s", 200, payload)
}

func (o *GetProjectsOK) GetPayload() *models.ResponseBodyProjects {
	return o.Payload
}

func (o *GetProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyProjects)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectsInternalServerError creates a GetProjectsInternalServerError with default headers values
func NewGetProjectsInternalServerError() *GetProjectsInternalServerError {
	return &GetProjectsInternalServerError{}
}

/*
GetProjectsInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetProjectsInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get projects internal server error response has a 2xx status code
func (o *GetProjectsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get projects internal server error response has a 3xx status code
func (o *GetProjectsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get projects internal server error response has a 4xx status code
func (o *GetProjectsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get projects internal server error response has a 5xx status code
func (o *GetProjectsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get projects internal server error response a status code equal to that given
func (o *GetProjectsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get projects internal server error response
func (o *GetProjectsInternalServerError) Code() int {
	return 500
}

func (o *GetProjectsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects][%d] getProjectsInternalServerError %s", 500, payload)
}

func (o *GetProjectsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects][%d] getProjectsInternalServerError %s", 500, payload)
}

func (o *GetProjectsInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetProjectsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
