// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/client/models"
)

// GetRrdsIDReader is a Reader for the GetRrdsID structure.
type GetRrdsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRrdsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRrdsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRrdsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRrdsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRrdsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /rrds/{id}] GetRrdsID", response, response.Code())
	}
}

// NewGetRrdsIDOK creates a GetRrdsIDOK with default headers values
func NewGetRrdsIDOK() *GetRrdsIDOK {
	return &GetRrdsIDOK{}
}

/*
GetRrdsIDOK describes a response with status code 200, with default header values.

success
*/
type GetRrdsIDOK struct {
	Payload *models.ResponseBodyRrdResource
}

// IsSuccess returns true when this get rrds Id o k response has a 2xx status code
func (o *GetRrdsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get rrds Id o k response has a 3xx status code
func (o *GetRrdsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rrds Id o k response has a 4xx status code
func (o *GetRrdsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get rrds Id o k response has a 5xx status code
func (o *GetRrdsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get rrds Id o k response a status code equal to that given
func (o *GetRrdsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get rrds Id o k response
func (o *GetRrdsIDOK) Code() int {
	return 200
}

func (o *GetRrdsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdOK %s", 200, payload)
}

func (o *GetRrdsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdOK %s", 200, payload)
}

func (o *GetRrdsIDOK) GetPayload() *models.ResponseBodyRrdResource {
	return o.Payload
}

func (o *GetRrdsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyRrdResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRrdsIDBadRequest creates a GetRrdsIDBadRequest with default headers values
func NewGetRrdsIDBadRequest() *GetRrdsIDBadRequest {
	return &GetRrdsIDBadRequest{}
}

/*
GetRrdsIDBadRequest describes a response with status code 400, with default header values.

bad request
*/
type GetRrdsIDBadRequest struct {
	Payload *models.ResponseBody400
}

// IsSuccess returns true when this get rrds Id bad request response has a 2xx status code
func (o *GetRrdsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rrds Id bad request response has a 3xx status code
func (o *GetRrdsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rrds Id bad request response has a 4xx status code
func (o *GetRrdsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get rrds Id bad request response has a 5xx status code
func (o *GetRrdsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get rrds Id bad request response a status code equal to that given
func (o *GetRrdsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get rrds Id bad request response
func (o *GetRrdsIDBadRequest) Code() int {
	return 400
}

func (o *GetRrdsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdBadRequest %s", 400, payload)
}

func (o *GetRrdsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdBadRequest %s", 400, payload)
}

func (o *GetRrdsIDBadRequest) GetPayload() *models.ResponseBody400 {
	return o.Payload
}

func (o *GetRrdsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRrdsIDNotFound creates a GetRrdsIDNotFound with default headers values
func NewGetRrdsIDNotFound() *GetRrdsIDNotFound {
	return &GetRrdsIDNotFound{}
}

/*
GetRrdsIDNotFound describes a response with status code 404, with default header values.

project not found
*/
type GetRrdsIDNotFound struct {
	Payload string
}

// IsSuccess returns true when this get rrds Id not found response has a 2xx status code
func (o *GetRrdsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rrds Id not found response has a 3xx status code
func (o *GetRrdsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rrds Id not found response has a 4xx status code
func (o *GetRrdsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get rrds Id not found response has a 5xx status code
func (o *GetRrdsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get rrds Id not found response a status code equal to that given
func (o *GetRrdsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get rrds Id not found response
func (o *GetRrdsIDNotFound) Code() int {
	return 404
}

func (o *GetRrdsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdNotFound %s", 404, payload)
}

func (o *GetRrdsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdNotFound %s", 404, payload)
}

func (o *GetRrdsIDNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetRrdsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRrdsIDInternalServerError creates a GetRrdsIDInternalServerError with default headers values
func NewGetRrdsIDInternalServerError() *GetRrdsIDInternalServerError {
	return &GetRrdsIDInternalServerError{}
}

/*
GetRrdsIDInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetRrdsIDInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get rrds Id internal server error response has a 2xx status code
func (o *GetRrdsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rrds Id internal server error response has a 3xx status code
func (o *GetRrdsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rrds Id internal server error response has a 4xx status code
func (o *GetRrdsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get rrds Id internal server error response has a 5xx status code
func (o *GetRrdsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get rrds Id internal server error response a status code equal to that given
func (o *GetRrdsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get rrds Id internal server error response
func (o *GetRrdsIDInternalServerError) Code() int {
	return 500
}

func (o *GetRrdsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdInternalServerError %s", 500, payload)
}

func (o *GetRrdsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds/{id}][%d] getRrdsIdInternalServerError %s", 500, payload)
}

func (o *GetRrdsIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetRrdsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
