// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/filer-gateway/pkg/swagger/client/models"
)

// GetUsersIDReader is a Reader for the GetUsersID structure.
type GetUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetUsersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUsersIDOK creates a GetUsersIDOK with default headers values
func NewGetUsersIDOK() *GetUsersIDOK {
	return &GetUsersIDOK{}
}

/*GetUsersIDOK handles this case with default header values.

success
*/
type GetUsersIDOK struct {
	Payload *models.ResponseBodyUserResource
}

func (o *GetUsersIDOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}][%d] getUsersIdOK  %+v", 200, o.Payload)
}

func (o *GetUsersIDOK) GetPayload() *models.ResponseBodyUserResource {
	return o.Payload
}

func (o *GetUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyUserResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersIDBadRequest creates a GetUsersIDBadRequest with default headers values
func NewGetUsersIDBadRequest() *GetUsersIDBadRequest {
	return &GetUsersIDBadRequest{}
}

/*GetUsersIDBadRequest handles this case with default header values.

bad request
*/
type GetUsersIDBadRequest struct {
	Payload *models.ResponseBody400
}

func (o *GetUsersIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /users/{id}][%d] getUsersIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetUsersIDBadRequest) GetPayload() *models.ResponseBody400 {
	return o.Payload
}

func (o *GetUsersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersIDNotFound creates a GetUsersIDNotFound with default headers values
func NewGetUsersIDNotFound() *GetUsersIDNotFound {
	return &GetUsersIDNotFound{}
}

/*GetUsersIDNotFound handles this case with default header values.

user not found
*/
type GetUsersIDNotFound struct {
	Payload string
}

func (o *GetUsersIDNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}][%d] getUsersIdNotFound  %+v", 404, o.Payload)
}

func (o *GetUsersIDNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersIDInternalServerError creates a GetUsersIDInternalServerError with default headers values
func NewGetUsersIDInternalServerError() *GetUsersIDInternalServerError {
	return &GetUsersIDInternalServerError{}
}

/*GetUsersIDInternalServerError handles this case with default header values.

failure
*/
type GetUsersIDInternalServerError struct {
	Payload *models.ResponseBody500
}

func (o *GetUsersIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{id}][%d] getUsersIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUsersIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
