// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRrdsParams creates a new GetRrdsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRrdsParams() *GetRrdsParams {
	return &GetRrdsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRrdsParamsWithTimeout creates a new GetRrdsParams object
// with the ability to set a timeout on a request.
func NewGetRrdsParamsWithTimeout(timeout time.Duration) *GetRrdsParams {
	return &GetRrdsParams{
		timeout: timeout,
	}
}

// NewGetRrdsParamsWithContext creates a new GetRrdsParams object
// with the ability to set a context for a request.
func NewGetRrdsParamsWithContext(ctx context.Context) *GetRrdsParams {
	return &GetRrdsParams{
		Context: ctx,
	}
}

// NewGetRrdsParamsWithHTTPClient creates a new GetRrdsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRrdsParamsWithHTTPClient(client *http.Client) *GetRrdsParams {
	return &GetRrdsParams{
		HTTPClient: client,
	}
}

/*
GetRrdsParams contains all the parameters to send to the API endpoint

	for the get rrds operation.

	Typically these are written to a http.Request.
*/
type GetRrdsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get rrds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRrdsParams) WithDefaults() *GetRrdsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get rrds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRrdsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get rrds params
func (o *GetRrdsParams) WithTimeout(timeout time.Duration) *GetRrdsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rrds params
func (o *GetRrdsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rrds params
func (o *GetRrdsParams) WithContext(ctx context.Context) *GetRrdsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rrds params
func (o *GetRrdsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rrds params
func (o *GetRrdsParams) WithHTTPClient(client *http.Client) *GetRrdsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rrds params
func (o *GetRrdsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRrdsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
