// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/client/models"
)

// GetRrdsReader is a Reader for the GetRrds structure.
type GetRrdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRrdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRrdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetRrdsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /rrds] GetRrds", response, response.Code())
	}
}

// NewGetRrdsOK creates a GetRrdsOK with default headers values
func NewGetRrdsOK() *GetRrdsOK {
	return &GetRrdsOK{}
}

/*
GetRrdsOK describes a response with status code 200, with default header values.

success
*/
type GetRrdsOK struct {
	Payload *models.ResponseBodyRrds
}

// IsSuccess returns true when this get rrds o k response has a 2xx status code
func (o *GetRrdsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get rrds o k response has a 3xx status code
func (o *GetRrdsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rrds o k response has a 4xx status code
func (o *GetRrdsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get rrds o k response has a 5xx status code
func (o *GetRrdsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get rrds o k response a status code equal to that given
func (o *GetRrdsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get rrds o k response
func (o *GetRrdsOK) Code() int {
	return 200
}

func (o *GetRrdsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds][%d] getRrdsOK %s", 200, payload)
}

func (o *GetRrdsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds][%d] getRrdsOK %s", 200, payload)
}

func (o *GetRrdsOK) GetPayload() *models.ResponseBodyRrds {
	return o.Payload
}

func (o *GetRrdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyRrds)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRrdsInternalServerError creates a GetRrdsInternalServerError with default headers values
func NewGetRrdsInternalServerError() *GetRrdsInternalServerError {
	return &GetRrdsInternalServerError{}
}

/*
GetRrdsInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetRrdsInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get rrds internal server error response has a 2xx status code
func (o *GetRrdsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rrds internal server error response has a 3xx status code
func (o *GetRrdsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rrds internal server error response has a 4xx status code
func (o *GetRrdsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get rrds internal server error response has a 5xx status code
func (o *GetRrdsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get rrds internal server error response a status code equal to that given
func (o *GetRrdsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get rrds internal server error response
func (o *GetRrdsInternalServerError) Code() int {
	return 500
}

func (o *GetRrdsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds][%d] getRrdsInternalServerError %s", 500, payload)
}

func (o *GetRrdsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rrds][%d] getRrdsInternalServerError %s", 500, payload)
}

func (o *GetRrdsInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetRrdsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
