// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersIDParams creates a new GetUsersIDParams object
// with the default values initialized.
func NewGetUsersIDParams() *GetUsersIDParams {
	var ()
	return &GetUsersIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersIDParamsWithTimeout creates a new GetUsersIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersIDParamsWithTimeout(timeout time.Duration) *GetUsersIDParams {
	var ()
	return &GetUsersIDParams{

		timeout: timeout,
	}
}

// NewGetUsersIDParamsWithContext creates a new GetUsersIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersIDParamsWithContext(ctx context.Context) *GetUsersIDParams {
	var ()
	return &GetUsersIDParams{

		Context: ctx,
	}
}

// NewGetUsersIDParamsWithHTTPClient creates a new GetUsersIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersIDParamsWithHTTPClient(client *http.Client) *GetUsersIDParams {
	var ()
	return &GetUsersIDParams{
		HTTPClient: client,
	}
}

/*GetUsersIDParams contains all the parameters to send to the API endpoint
for the get users ID operation typically these are written to a http.Request
*/
type GetUsersIDParams struct {

	/*ID
	  user identifier

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users ID params
func (o *GetUsersIDParams) WithTimeout(timeout time.Duration) *GetUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users ID params
func (o *GetUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users ID params
func (o *GetUsersIDParams) WithContext(ctx context.Context) *GetUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users ID params
func (o *GetUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users ID params
func (o *GetUsersIDParams) WithHTTPClient(client *http.Client) *GetUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users ID params
func (o *GetUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get users ID params
func (o *GetUsersIDParams) WithID(id string) *GetUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get users ID params
func (o *GetUsersIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
