// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRrdsIDParams creates a new GetRrdsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRrdsIDParams() *GetRrdsIDParams {
	return &GetRrdsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRrdsIDParamsWithTimeout creates a new GetRrdsIDParams object
// with the ability to set a timeout on a request.
func NewGetRrdsIDParamsWithTimeout(timeout time.Duration) *GetRrdsIDParams {
	return &GetRrdsIDParams{
		timeout: timeout,
	}
}

// NewGetRrdsIDParamsWithContext creates a new GetRrdsIDParams object
// with the ability to set a context for a request.
func NewGetRrdsIDParamsWithContext(ctx context.Context) *GetRrdsIDParams {
	return &GetRrdsIDParams{
		Context: ctx,
	}
}

// NewGetRrdsIDParamsWithHTTPClient creates a new GetRrdsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRrdsIDParamsWithHTTPClient(client *http.Client) *GetRrdsIDParams {
	return &GetRrdsIDParams{
		HTTPClient: client,
	}
}

/*
GetRrdsIDParams contains all the parameters to send to the API endpoint

	for the get rrds ID operation.

	Typically these are written to a http.Request.
*/
type GetRrdsIDParams struct {

	/* ID.

	   project identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get rrds ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRrdsIDParams) WithDefaults() *GetRrdsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get rrds ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRrdsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get rrds ID params
func (o *GetRrdsIDParams) WithTimeout(timeout time.Duration) *GetRrdsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rrds ID params
func (o *GetRrdsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rrds ID params
func (o *GetRrdsIDParams) WithContext(ctx context.Context) *GetRrdsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rrds ID params
func (o *GetRrdsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rrds ID params
func (o *GetRrdsIDParams) WithHTTPClient(client *http.Client) *GetRrdsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rrds ID params
func (o *GetRrdsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get rrds ID params
func (o *GetRrdsIDParams) WithID(id string) *GetRrdsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get rrds ID params
func (o *GetRrdsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRrdsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
