// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/client/models"
)

// NewPostRrdsParams creates a new PostRrdsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRrdsParams() *PostRrdsParams {
	return &PostRrdsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRrdsParamsWithTimeout creates a new PostRrdsParams object
// with the ability to set a timeout on a request.
func NewPostRrdsParamsWithTimeout(timeout time.Duration) *PostRrdsParams {
	return &PostRrdsParams{
		timeout: timeout,
	}
}

// NewPostRrdsParamsWithContext creates a new PostRrdsParams object
// with the ability to set a context for a request.
func NewPostRrdsParamsWithContext(ctx context.Context) *PostRrdsParams {
	return &PostRrdsParams{
		Context: ctx,
	}
}

// NewPostRrdsParamsWithHTTPClient creates a new PostRrdsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRrdsParamsWithHTTPClient(client *http.Client) *PostRrdsParams {
	return &PostRrdsParams{
		HTTPClient: client,
	}
}

/*
PostRrdsParams contains all the parameters to send to the API endpoint

	for the post rrds operation.

	Typically these are written to a http.Request.
*/
type PostRrdsParams struct {

	/* RrdProvisionData.

	   data for rrd storage provisioning
	*/
	RrdProvisionData *models.RequestBodyRrdProvision

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post rrds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRrdsParams) WithDefaults() *PostRrdsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post rrds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRrdsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post rrds params
func (o *PostRrdsParams) WithTimeout(timeout time.Duration) *PostRrdsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post rrds params
func (o *PostRrdsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post rrds params
func (o *PostRrdsParams) WithContext(ctx context.Context) *PostRrdsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post rrds params
func (o *PostRrdsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post rrds params
func (o *PostRrdsParams) WithHTTPClient(client *http.Client) *PostRrdsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post rrds params
func (o *PostRrdsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRrdProvisionData adds the rrdProvisionData to the post rrds params
func (o *PostRrdsParams) WithRrdProvisionData(rrdProvisionData *models.RequestBodyRrdProvision) *PostRrdsParams {
	o.SetRrdProvisionData(rrdProvisionData)
	return o
}

// SetRrdProvisionData adds the rrdProvisionData to the post rrds params
func (o *PostRrdsParams) SetRrdProvisionData(rrdProvisionData *models.RequestBodyRrdProvision) {
	o.RrdProvisionData = rrdProvisionData
}

// WriteToRequest writes these params to a swagger request
func (o *PostRrdsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RrdProvisionData != nil {
		if err := r.SetBodyParam(o.RrdProvisionData); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
