// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/client/models"
)

// PostRrdsReader is a Reader for the PostRrds structure.
type PostRrdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRrdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRrdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostRrdsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostRrdsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /rrds] PostRrds", response, response.Code())
	}
}

// NewPostRrdsOK creates a PostRrdsOK with default headers values
func NewPostRrdsOK() *PostRrdsOK {
	return &PostRrdsOK{}
}

/*
PostRrdsOK describes a response with status code 200, with default header values.

success
*/
type PostRrdsOK struct {
	Payload *models.ResponseBodyTaskResource
}

// IsSuccess returns true when this post rrds o k response has a 2xx status code
func (o *PostRrdsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post rrds o k response has a 3xx status code
func (o *PostRrdsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post rrds o k response has a 4xx status code
func (o *PostRrdsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post rrds o k response has a 5xx status code
func (o *PostRrdsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post rrds o k response a status code equal to that given
func (o *PostRrdsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post rrds o k response
func (o *PostRrdsOK) Code() int {
	return 200
}

func (o *PostRrdsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /rrds][%d] postRrdsOK %s", 200, payload)
}

func (o *PostRrdsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /rrds][%d] postRrdsOK %s", 200, payload)
}

func (o *PostRrdsOK) GetPayload() *models.ResponseBodyTaskResource {
	return o.Payload
}

func (o *PostRrdsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyTaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRrdsBadRequest creates a PostRrdsBadRequest with default headers values
func NewPostRrdsBadRequest() *PostRrdsBadRequest {
	return &PostRrdsBadRequest{}
}

/*
PostRrdsBadRequest describes a response with status code 400, with default header values.

bad request
*/
type PostRrdsBadRequest struct {
	Payload *models.ResponseBody400
}

// IsSuccess returns true when this post rrds bad request response has a 2xx status code
func (o *PostRrdsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post rrds bad request response has a 3xx status code
func (o *PostRrdsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post rrds bad request response has a 4xx status code
func (o *PostRrdsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post rrds bad request response has a 5xx status code
func (o *PostRrdsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post rrds bad request response a status code equal to that given
func (o *PostRrdsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post rrds bad request response
func (o *PostRrdsBadRequest) Code() int {
	return 400
}

func (o *PostRrdsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /rrds][%d] postRrdsBadRequest %s", 400, payload)
}

func (o *PostRrdsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /rrds][%d] postRrdsBadRequest %s", 400, payload)
}

func (o *PostRrdsBadRequest) GetPayload() *models.ResponseBody400 {
	return o.Payload
}

func (o *PostRrdsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody400)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRrdsInternalServerError creates a PostRrdsInternalServerError with default headers values
func NewPostRrdsInternalServerError() *PostRrdsInternalServerError {
	return &PostRrdsInternalServerError{}
}

/*
PostRrdsInternalServerError describes a response with status code 500, with default header values.

failure
*/
type PostRrdsInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this post rrds internal server error response has a 2xx status code
func (o *PostRrdsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post rrds internal server error response has a 3xx status code
func (o *PostRrdsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post rrds internal server error response has a 4xx status code
func (o *PostRrdsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post rrds internal server error response has a 5xx status code
func (o *PostRrdsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post rrds internal server error response a status code equal to that given
func (o *PostRrdsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post rrds internal server error response
func (o *PostRrdsInternalServerError) Code() int {
	return 500
}

func (o *PostRrdsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /rrds][%d] postRrdsInternalServerError %s", 500, payload)
}

func (o *PostRrdsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /rrds][%d] postRrdsInternalServerError %s", 500, payload)
}

func (o *PostRrdsInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *PostRrdsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
