// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/server/models"
)

// DeleteUsersIDOKCode is the HTTP code returned for type DeleteUsersIDOK
const DeleteUsersIDOKCode int = 200

/*
DeleteUsersIDOK success

swagger:response deleteUsersIdOK
*/
type DeleteUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyTaskResource `json:"body,omitempty"`
}

// NewDeleteUsersIDOK creates DeleteUsersIDOK with default headers values
func NewDeleteUsersIDOK() *DeleteUsersIDOK {

	return &DeleteUsersIDOK{}
}

// WithPayload adds the payload to the delete users Id o k response
func (o *DeleteUsersIDOK) WithPayload(payload *models.ResponseBodyTaskResource) *DeleteUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id o k response
func (o *DeleteUsersIDOK) SetPayload(payload *models.ResponseBodyTaskResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsersIDBadRequestCode is the HTTP code returned for type DeleteUsersIDBadRequest
const DeleteUsersIDBadRequestCode int = 400

/*
DeleteUsersIDBadRequest bad request

swagger:response deleteUsersIdBadRequest
*/
type DeleteUsersIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewDeleteUsersIDBadRequest creates DeleteUsersIDBadRequest with default headers values
func NewDeleteUsersIDBadRequest() *DeleteUsersIDBadRequest {

	return &DeleteUsersIDBadRequest{}
}

// WithPayload adds the payload to the delete users Id bad request response
func (o *DeleteUsersIDBadRequest) WithPayload(payload *models.ResponseBody400) *DeleteUsersIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id bad request response
func (o *DeleteUsersIDBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsersIDNotFoundCode is the HTTP code returned for type DeleteUsersIDNotFound
const DeleteUsersIDNotFoundCode int = 404

/*
DeleteUsersIDNotFound user not found

swagger:response deleteUsersIdNotFound
*/
type DeleteUsersIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteUsersIDNotFound creates DeleteUsersIDNotFound with default headers values
func NewDeleteUsersIDNotFound() *DeleteUsersIDNotFound {

	return &DeleteUsersIDNotFound{}
}

// WithPayload adds the payload to the delete users Id not found response
func (o *DeleteUsersIDNotFound) WithPayload(payload string) *DeleteUsersIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id not found response
func (o *DeleteUsersIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteUsersIDInternalServerErrorCode is the HTTP code returned for type DeleteUsersIDInternalServerError
const DeleteUsersIDInternalServerErrorCode int = 500

/*
DeleteUsersIDInternalServerError failure

swagger:response deleteUsersIdInternalServerError
*/
type DeleteUsersIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewDeleteUsersIDInternalServerError creates DeleteUsersIDInternalServerError with default headers values
func NewDeleteUsersIDInternalServerError() *DeleteUsersIDInternalServerError {

	return &DeleteUsersIDInternalServerError{}
}

// WithPayload adds the payload to the delete users Id internal server error response
func (o *DeleteUsersIDInternalServerError) WithPayload(payload *models.ResponseBody500) *DeleteUsersIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id internal server error response
func (o *DeleteUsersIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
