// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/server/models"
)

// GetRrdsIDOKCode is the HTTP code returned for type GetRrdsIDOK
const GetRrdsIDOKCode int = 200

/*
GetRrdsIDOK success

swagger:response getRrdsIdOK
*/
type GetRrdsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyRrdResource `json:"body,omitempty"`
}

// NewGetRrdsIDOK creates GetRrdsIDOK with default headers values
func NewGetRrdsIDOK() *GetRrdsIDOK {

	return &GetRrdsIDOK{}
}

// WithPayload adds the payload to the get rrds Id o k response
func (o *GetRrdsIDOK) WithPayload(payload *models.ResponseBodyRrdResource) *GetRrdsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rrds Id o k response
func (o *GetRrdsIDOK) SetPayload(payload *models.ResponseBodyRrdResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRrdsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRrdsIDBadRequestCode is the HTTP code returned for type GetRrdsIDBadRequest
const GetRrdsIDBadRequestCode int = 400

/*
GetRrdsIDBadRequest bad request

swagger:response getRrdsIdBadRequest
*/
type GetRrdsIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewGetRrdsIDBadRequest creates GetRrdsIDBadRequest with default headers values
func NewGetRrdsIDBadRequest() *GetRrdsIDBadRequest {

	return &GetRrdsIDBadRequest{}
}

// WithPayload adds the payload to the get rrds Id bad request response
func (o *GetRrdsIDBadRequest) WithPayload(payload *models.ResponseBody400) *GetRrdsIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rrds Id bad request response
func (o *GetRrdsIDBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRrdsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRrdsIDNotFoundCode is the HTTP code returned for type GetRrdsIDNotFound
const GetRrdsIDNotFoundCode int = 404

/*
GetRrdsIDNotFound project not found

swagger:response getRrdsIdNotFound
*/
type GetRrdsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRrdsIDNotFound creates GetRrdsIDNotFound with default headers values
func NewGetRrdsIDNotFound() *GetRrdsIDNotFound {

	return &GetRrdsIDNotFound{}
}

// WithPayload adds the payload to the get rrds Id not found response
func (o *GetRrdsIDNotFound) WithPayload(payload string) *GetRrdsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rrds Id not found response
func (o *GetRrdsIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRrdsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRrdsIDInternalServerErrorCode is the HTTP code returned for type GetRrdsIDInternalServerError
const GetRrdsIDInternalServerErrorCode int = 500

/*
GetRrdsIDInternalServerError failure

swagger:response getRrdsIdInternalServerError
*/
type GetRrdsIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetRrdsIDInternalServerError creates GetRrdsIDInternalServerError with default headers values
func NewGetRrdsIDInternalServerError() *GetRrdsIDInternalServerError {

	return &GetRrdsIDInternalServerError{}
}

// WithPayload adds the payload to the get rrds Id internal server error response
func (o *GetRrdsIDInternalServerError) WithPayload(payload *models.ResponseBody500) *GetRrdsIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rrds Id internal server error response
func (o *GetRrdsIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRrdsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
