// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/filer-gateway/pkg/swagger/server/models"
)

// GetTasksTypeIDOKCode is the HTTP code returned for type GetTasksTypeIDOK
const GetTasksTypeIDOKCode int = 200

/*
GetTasksTypeIDOK success

swagger:response getTasksTypeIdOK
*/
type GetTasksTypeIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyTaskResource `json:"body,omitempty"`
}

// NewGetTasksTypeIDOK creates GetTasksTypeIDOK with default headers values
func NewGetTasksTypeIDOK() *GetTasksTypeIDOK {

	return &GetTasksTypeIDOK{}
}

// WithPayload adds the payload to the get tasks type Id o k response
func (o *GetTasksTypeIDOK) WithPayload(payload *models.ResponseBodyTaskResource) *GetTasksTypeIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks type Id o k response
func (o *GetTasksTypeIDOK) SetPayload(payload *models.ResponseBodyTaskResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksTypeIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTasksTypeIDBadRequestCode is the HTTP code returned for type GetTasksTypeIDBadRequest
const GetTasksTypeIDBadRequestCode int = 400

/*
GetTasksTypeIDBadRequest bad request

swagger:response getTasksTypeIdBadRequest
*/
type GetTasksTypeIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewGetTasksTypeIDBadRequest creates GetTasksTypeIDBadRequest with default headers values
func NewGetTasksTypeIDBadRequest() *GetTasksTypeIDBadRequest {

	return &GetTasksTypeIDBadRequest{}
}

// WithPayload adds the payload to the get tasks type Id bad request response
func (o *GetTasksTypeIDBadRequest) WithPayload(payload *models.ResponseBody400) *GetTasksTypeIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks type Id bad request response
func (o *GetTasksTypeIDBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksTypeIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTasksTypeIDNotFoundCode is the HTTP code returned for type GetTasksTypeIDNotFound
const GetTasksTypeIDNotFoundCode int = 404

/*
GetTasksTypeIDNotFound task not found

swagger:response getTasksTypeIdNotFound
*/
type GetTasksTypeIDNotFound struct {
}

// NewGetTasksTypeIDNotFound creates GetTasksTypeIDNotFound with default headers values
func NewGetTasksTypeIDNotFound() *GetTasksTypeIDNotFound {

	return &GetTasksTypeIDNotFound{}
}

// WriteResponse to the client
func (o *GetTasksTypeIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTasksTypeIDInternalServerErrorCode is the HTTP code returned for type GetTasksTypeIDInternalServerError
const GetTasksTypeIDInternalServerErrorCode int = 500

/*
GetTasksTypeIDInternalServerError failure

swagger:response getTasksTypeIdInternalServerError
*/
type GetTasksTypeIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetTasksTypeIDInternalServerError creates GetTasksTypeIDInternalServerError with default headers values
func NewGetTasksTypeIDInternalServerError() *GetTasksTypeIDInternalServerError {

	return &GetTasksTypeIDInternalServerError{}
}

// WithPayload adds the payload to the get tasks type Id internal server error response
func (o *GetTasksTypeIDInternalServerError) WithPayload(payload *models.ResponseBody500) *GetTasksTypeIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks type Id internal server error response
func (o *GetTasksTypeIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksTypeIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
