// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRrdsHandlerFunc turns a function with the right signature into a get rrds handler
type GetRrdsHandlerFunc func(GetRrdsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRrdsHandlerFunc) Handle(params GetRrdsParams) middleware.Responder {
	return fn(params)
}

// GetRrdsHandler interface for that can handle valid get rrds params
type GetRrdsHandler interface {
	Handle(GetRrdsParams) middleware.Responder
}

// NewGetRrds creates a new http.Handler for the get rrds operation
func NewGetRrds(ctx *middleware.Context, handler GetRrdsHandler) *GetRrds {
	return &GetRrds{Context: ctx, Handler: handler}
}

/*
	GetRrds swagger:route GET /rrds getRrds

get filer resources of all research-related data storage.
*/
type GetRrds struct {
	Context *middleware.Context
	Handler GetRrdsHandler
}

func (o *GetRrds) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRrdsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
