// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/filer-gateway/pkg/swagger/server/models"
)

// GetUsersIDOKCode is the HTTP code returned for type GetUsersIDOK
const GetUsersIDOKCode int = 200

/*GetUsersIDOK success

swagger:response getUsersIdOK
*/
type GetUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyUserResource `json:"body,omitempty"`
}

// NewGetUsersIDOK creates GetUsersIDOK with default headers values
func NewGetUsersIDOK() *GetUsersIDOK {

	return &GetUsersIDOK{}
}

// WithPayload adds the payload to the get users Id o k response
func (o *GetUsersIDOK) WithPayload(payload *models.ResponseBodyUserResource) *GetUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id o k response
func (o *GetUsersIDOK) SetPayload(payload *models.ResponseBodyUserResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersIDBadRequestCode is the HTTP code returned for type GetUsersIDBadRequest
const GetUsersIDBadRequestCode int = 400

/*GetUsersIDBadRequest bad request

swagger:response getUsersIdBadRequest
*/
type GetUsersIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewGetUsersIDBadRequest creates GetUsersIDBadRequest with default headers values
func NewGetUsersIDBadRequest() *GetUsersIDBadRequest {

	return &GetUsersIDBadRequest{}
}

// WithPayload adds the payload to the get users Id bad request response
func (o *GetUsersIDBadRequest) WithPayload(payload *models.ResponseBody400) *GetUsersIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id bad request response
func (o *GetUsersIDBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersIDNotFoundCode is the HTTP code returned for type GetUsersIDNotFound
const GetUsersIDNotFoundCode int = 404

/*GetUsersIDNotFound user not found

swagger:response getUsersIdNotFound
*/
type GetUsersIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetUsersIDNotFound creates GetUsersIDNotFound with default headers values
func NewGetUsersIDNotFound() *GetUsersIDNotFound {

	return &GetUsersIDNotFound{}
}

// WithPayload adds the payload to the get users Id not found response
func (o *GetUsersIDNotFound) WithPayload(payload string) *GetUsersIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id not found response
func (o *GetUsersIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUsersIDInternalServerErrorCode is the HTTP code returned for type GetUsersIDInternalServerError
const GetUsersIDInternalServerErrorCode int = 500

/*GetUsersIDInternalServerError failure

swagger:response getUsersIdInternalServerError
*/
type GetUsersIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetUsersIDInternalServerError creates GetUsersIDInternalServerError with default headers values
func NewGetUsersIDInternalServerError() *GetUsersIDInternalServerError {

	return &GetUsersIDInternalServerError{}
}

// WithPayload adds the payload to the get users Id internal server error response
func (o *GetUsersIDInternalServerError) WithPayload(payload *models.ResponseBody500) *GetUsersIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id internal server error response
func (o *GetUsersIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
