// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/filer-gateway/pkg/swagger/server/models"
)

// PatchProjectsIDOKCode is the HTTP code returned for type PatchProjectsIDOK
const PatchProjectsIDOKCode int = 200

/*PatchProjectsIDOK success

swagger:response patchProjectsIdOK
*/
type PatchProjectsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyTaskResource `json:"body,omitempty"`
}

// NewPatchProjectsIDOK creates PatchProjectsIDOK with default headers values
func NewPatchProjectsIDOK() *PatchProjectsIDOK {

	return &PatchProjectsIDOK{}
}

// WithPayload adds the payload to the patch projects Id o k response
func (o *PatchProjectsIDOK) WithPayload(payload *models.ResponseBodyTaskResource) *PatchProjectsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch projects Id o k response
func (o *PatchProjectsIDOK) SetPayload(payload *models.ResponseBodyTaskResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchProjectsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchProjectsIDBadRequestCode is the HTTP code returned for type PatchProjectsIDBadRequest
const PatchProjectsIDBadRequestCode int = 400

/*PatchProjectsIDBadRequest bad request

swagger:response patchProjectsIdBadRequest
*/
type PatchProjectsIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewPatchProjectsIDBadRequest creates PatchProjectsIDBadRequest with default headers values
func NewPatchProjectsIDBadRequest() *PatchProjectsIDBadRequest {

	return &PatchProjectsIDBadRequest{}
}

// WithPayload adds the payload to the patch projects Id bad request response
func (o *PatchProjectsIDBadRequest) WithPayload(payload *models.ResponseBody400) *PatchProjectsIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch projects Id bad request response
func (o *PatchProjectsIDBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchProjectsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchProjectsIDNotFoundCode is the HTTP code returned for type PatchProjectsIDNotFound
const PatchProjectsIDNotFoundCode int = 404

/*PatchProjectsIDNotFound project not found

swagger:response patchProjectsIdNotFound
*/
type PatchProjectsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPatchProjectsIDNotFound creates PatchProjectsIDNotFound with default headers values
func NewPatchProjectsIDNotFound() *PatchProjectsIDNotFound {

	return &PatchProjectsIDNotFound{}
}

// WithPayload adds the payload to the patch projects Id not found response
func (o *PatchProjectsIDNotFound) WithPayload(payload string) *PatchProjectsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch projects Id not found response
func (o *PatchProjectsIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchProjectsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PatchProjectsIDInternalServerErrorCode is the HTTP code returned for type PatchProjectsIDInternalServerError
const PatchProjectsIDInternalServerErrorCode int = 500

/*PatchProjectsIDInternalServerError failure

swagger:response patchProjectsIdInternalServerError
*/
type PatchProjectsIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewPatchProjectsIDInternalServerError creates PatchProjectsIDInternalServerError with default headers values
func NewPatchProjectsIDInternalServerError() *PatchProjectsIDInternalServerError {

	return &PatchProjectsIDInternalServerError{}
}

// WithPayload adds the payload to the patch projects Id internal server error response
func (o *PatchProjectsIDInternalServerError) WithPayload(payload *models.ResponseBody500) *PatchProjectsIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch projects Id internal server error response
func (o *PatchProjectsIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchProjectsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
