// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchUsersIDHandlerFunc turns a function with the right signature into a patch users ID handler
type PatchUsersIDHandlerFunc func(PatchUsersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUsersIDHandlerFunc) Handle(params PatchUsersIDParams) middleware.Responder {
	return fn(params)
}

// PatchUsersIDHandler interface for that can handle valid patch users ID params
type PatchUsersIDHandler interface {
	Handle(PatchUsersIDParams) middleware.Responder
}

// NewPatchUsersID creates a new http.Handler for the patch users ID operation
func NewPatchUsersID(ctx *middleware.Context, handler PatchUsersIDHandler) *PatchUsersID {
	return &PatchUsersID{Context: ctx, Handler: handler}
}

/*PatchUsersID swagger:route PATCH /users/{id} patchUsersId

update filer resource for an existing user.

*/
type PatchUsersID struct {
	Context *middleware.Context
	Handler PatchUsersIDHandler
}

func (o *PatchUsersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchUsersIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
