// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/Donders-Institute/filer-gateway/pkg/swagger/server/models"
)

// NewPostProjectsParams creates a new PostProjectsParams object
// no default values defined in spec.
func NewPostProjectsParams() PostProjectsParams {

	return PostProjectsParams{}
}

// PostProjectsParams contains all the bound params for the post projects operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostProjects
type PostProjectsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*data for project provisioning
	  Required: true
	  In: body
	*/
	ProjectProvisionData *models.RequestBodyProjectProvision
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostProjectsParams() beforehand.
func (o *PostProjectsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RequestBodyProjectProvision
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("projectProvisionData", "body", ""))
			} else {
				res = append(res, errors.NewParseError("projectProvisionData", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ProjectProvisionData = &body
			}
		}
	} else {
		res = append(res, errors.Required("projectProvisionData", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
