// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dccn-tg/filer-gateway/pkg/swagger/server/models"
)

// PostRrdsOKCode is the HTTP code returned for type PostRrdsOK
const PostRrdsOKCode int = 200

/*
PostRrdsOK success

swagger:response postRrdsOK
*/
type PostRrdsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyTaskResource `json:"body,omitempty"`
}

// NewPostRrdsOK creates PostRrdsOK with default headers values
func NewPostRrdsOK() *PostRrdsOK {

	return &PostRrdsOK{}
}

// WithPayload adds the payload to the post rrds o k response
func (o *PostRrdsOK) WithPayload(payload *models.ResponseBodyTaskResource) *PostRrdsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rrds o k response
func (o *PostRrdsOK) SetPayload(payload *models.ResponseBodyTaskResource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRrdsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRrdsBadRequestCode is the HTTP code returned for type PostRrdsBadRequest
const PostRrdsBadRequestCode int = 400

/*
PostRrdsBadRequest bad request

swagger:response postRrdsBadRequest
*/
type PostRrdsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody400 `json:"body,omitempty"`
}

// NewPostRrdsBadRequest creates PostRrdsBadRequest with default headers values
func NewPostRrdsBadRequest() *PostRrdsBadRequest {

	return &PostRrdsBadRequest{}
}

// WithPayload adds the payload to the post rrds bad request response
func (o *PostRrdsBadRequest) WithPayload(payload *models.ResponseBody400) *PostRrdsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rrds bad request response
func (o *PostRrdsBadRequest) SetPayload(payload *models.ResponseBody400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRrdsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRrdsInternalServerErrorCode is the HTTP code returned for type PostRrdsInternalServerError
const PostRrdsInternalServerErrorCode int = 500

/*
PostRrdsInternalServerError failure

swagger:response postRrdsInternalServerError
*/
type PostRrdsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewPostRrdsInternalServerError creates PostRrdsInternalServerError with default headers values
func NewPostRrdsInternalServerError() *PostRrdsInternalServerError {

	return &PostRrdsInternalServerError{}
}

// WithPayload adds the payload to the post rrds internal server error response
func (o *PostRrdsInternalServerError) WithPayload(payload *models.ResponseBody500) *PostRrdsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post rrds internal server error response
func (o *PostRrdsInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRrdsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
