netapp:
  apiURL: https://131.174.44.94
  apiUser: gatewayadmin
  apiPass:
  projectRoot: /project
  projectUID: 1010
  projectGID: 1010
  projectMode: "volume"
  vserver: "atreides"
  exportPolicyHome: "dccn-home-nfs-vpn"
  exportPolicyProject: "dccn-projects"

freenas:
  apiURL: https://freenas.dccn.nl/api/v2.0
  apiUser: root
  apiPass:
  projectRoot: /project_freenas
  projectUser: project
  projectGroup: project_g
  zfsDatasetPrefix: zpool001/project

cephfs:
  projectRoot: /project_cephfs
  projectUser: project
  projectGroup: project_g

# configuration for connecting the SMTP server for notifications.
smtp:
  host: localhost
  port: 25
  auth_plain_user: ""
  auth_plain_pass: ""

# configuration for connecting the project database.
pdb:
  version: 1
  v1:
    db_host: "db.intranet.dccn.nl"
    db_port: 3306
    db_user: "acl"
    db_pass: ""
    db_name: "fcdc"
  v2:
    auth_client_secret: ""
    auth_url: "https://auth-dev.dccn.nl"
    core_api_url: "http://dccn-pl001.dccn.nl:4334/graphql"