// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ProjectID project identifier.
//
// swagger:model projectID
type ProjectID string

// Validate validates this project ID
func (m ProjectID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project ID based on context it is used
func (m ProjectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
