// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ProjectID project identifier.
// swagger:model projectID
type ProjectID string

// Validate validates this project ID
func (m ProjectID) Validate(formats strfmt.Registry) error {
	return nil
}
