// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseBody400 JSON object containing error message concerning bad client request.
//
// swagger:model responseBody400
type ResponseBody400 struct {

	// error message specifying the bad request.
	ErrorMessage string `json:"errorMessage,omitempty"`
}

// Validate validates this response body400
func (m *ResponseBody400) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseBody400) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseBody400) UnmarshalBinary(b []byte) error {
	var res ResponseBody400
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
