// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResponseBodyProjectMembers JSON object containing current list of members implemented on the filer.
// swagger:model responseBodyProjectMembers
type ResponseBodyProjectMembers struct {

	// members
	// Required: true
	Members Members `json:"members"`

	// project ID
	// Required: true
	ProjectID ProjectID `json:"projectID"`
}

// Validate validates this response body project members
func (m *ResponseBodyProjectMembers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMembers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseBodyProjectMembers) validateMembers(formats strfmt.Registry) error {

	if err := validate.Required("members", "body", m.Members); err != nil {
		return err
	}

	if err := m.Members.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("members")
		}
		return err
	}

	return nil
}

func (m *ResponseBodyProjectMembers) validateProjectID(formats strfmt.Registry) error {

	if err := m.ProjectID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("projectID")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponseBodyProjectMembers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseBodyProjectMembers) UnmarshalBinary(b []byte) error {
	var res ResponseBodyProjectMembers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
