// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StoragePatchRequest Data for updating storage resource.
//
// swagger:model storagePatchRequest
type StoragePatchRequest struct {

	// storage quota in GiB.
	// Required: true
	QuotaGb *int64 `json:"quotaGb"`
}

// Validate validates this storage patch request
func (m *StoragePatchRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuotaGb(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StoragePatchRequest) validateQuotaGb(formats strfmt.Registry) error {

	if err := validate.Required("quotaGb", "body", m.QuotaGb); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this storage patch request based on context it is used
func (m *StoragePatchRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoragePatchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoragePatchRequest) UnmarshalBinary(b []byte) error {
	var res StoragePatchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
