// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Storage JSON object for storage resource data.
// swagger:model storage
type Storage struct {

	// storage quota in GiB.
	// Required: true
	QuotaGb *int64 `json:"quotaGb"`

	// the targeting filer on which the storage resource is allocated.
	// Required: true
	// Enum: [netapp freenas ceph]
	System *string `json:"system"`

	// used quota size in GiB.
	// Required: true
	UsageGb *int64 `json:"usageGb"`
}

// Validate validates this storage
func (m *Storage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuotaGb(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSystem(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsageGb(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Storage) validateQuotaGb(formats strfmt.Registry) error {

	if err := validate.Required("quotaGb", "body", m.QuotaGb); err != nil {
		return err
	}

	return nil
}

var storageTypeSystemPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["netapp","freenas","ceph"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		storageTypeSystemPropEnum = append(storageTypeSystemPropEnum, v)
	}
}

const (

	// StorageSystemNetapp captures enum value "netapp"
	StorageSystemNetapp string = "netapp"

	// StorageSystemFreenas captures enum value "freenas"
	StorageSystemFreenas string = "freenas"

	// StorageSystemCeph captures enum value "ceph"
	StorageSystemCeph string = "ceph"
)

// prop value enum
func (m *Storage) validateSystemEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, storageTypeSystemPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Storage) validateSystem(formats strfmt.Registry) error {

	if err := validate.Required("system", "body", m.System); err != nil {
		return err
	}

	// value enum
	if err := m.validateSystemEnum("system", "body", *m.System); err != nil {
		return err
	}

	return nil
}

func (m *Storage) validateUsageGb(formats strfmt.Registry) error {

	if err := validate.Required("usageGb", "body", m.UsageGb); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Storage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Storage) UnmarshalBinary(b []byte) error {
	var res Storage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
