// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TaskStatus status of the background task.
// swagger:model taskStatus
type TaskStatus string

// Validate validates this task status
func (m TaskStatus) Validate(formats strfmt.Registry) error {
	return nil
}
